name: sklearn-diabetes
channels:
  - defaults
dependencies:
  - python=3.6.2
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
    - mlflow
    - azureml-mlflow
    - azureml-defaults
    - matplotlib
