model:
  name: autolog
  version: 1
  local_path: ./autolog_nyc_taxi
mini_batch_size: 1
output_configuration:
  output_action: append_row
  append_row_file_name: predictions.txt
retry_settings:
  max_retries: 3
  timeout: 30
error_threshold: -1 
logging_level: info
compute:
  target: azureml:cpuCompute
  instance_count: 1