# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import Any, Optional, TYPE_CHECKING

from azure.mgmt.core import AsyncARMPipelineClient
from msrest import Deserializer, Serializer

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from azure.core.credentials_async import AsyncTokenCredential

from ._configuration import AzureMachineLearningWorkspacesConfiguration
from .operations import BatchDeploymentOperations
from .operations import BatchEndpointOperations
from .operations import CodeContainerOperations
from .operations import CodeJobOperations
from .operations import CodeVersionOperations
from .operations import CustomAssetContainerOperations
from .operations import CustomAssetVersionOperations
from .operations import DataContainerOperations
from .operations import DatastoreOperations
from .operations import DataVersionOperations
from .operations import EnvironmentContainerOperations
from .operations import EnvironmentSpecificationVersionOperations
from .operations import JobOperations
from .operations import LabelingJobOperations
from .operations import ModelContainerOperations
from .operations import ModelVersionOperations
from .operations import OnlineDeploymentOperations
from .operations import OnlineEndpointOperations
from .operations import EventOperations
from .operations import ExperimentOperations
from .operations import RunOperations
from .operations import RunMetricOperations
from .operations import RunArtifactOperations
from .operations import OperationOperations
from .operations import WorkspaceOperations
from .operations import WorkspaceFeatureOperations
from .operations import UsageOperations
from .operations import VirtualMachineSizeOperations
from .operations import QuotaOperations
from .operations import MachineLearningComputeOperations
from .operations import SkuOperations
from .operations import PrivateEndpointConnectionOperations
from .operations import PrivateLinkResourceOperations
from .operations import LinkedWorkspaceOperations
from .operations import MachineLearningServiceOperations
from .. import models


class AzureMachineLearningWorkspaces(object):
    """These APIs allow end users to operate on Azure Machine Learning Workspace resources.

    :ivar batch_deployment: BatchDeploymentOperations operations
    :vartype batch_deployment: azure_machine_learning_workspaces.aio.operations.BatchDeploymentOperations
    :ivar batch_endpoint: BatchEndpointOperations operations
    :vartype batch_endpoint: azure_machine_learning_workspaces.aio.operations.BatchEndpointOperations
    :ivar code_container: CodeContainerOperations operations
    :vartype code_container: azure_machine_learning_workspaces.aio.operations.CodeContainerOperations
    :ivar code_job: CodeJobOperations operations
    :vartype code_job: azure_machine_learning_workspaces.aio.operations.CodeJobOperations
    :ivar code_version: CodeVersionOperations operations
    :vartype code_version: azure_machine_learning_workspaces.aio.operations.CodeVersionOperations
    :ivar custom_asset_container: CustomAssetContainerOperations operations
    :vartype custom_asset_container: azure_machine_learning_workspaces.aio.operations.CustomAssetContainerOperations
    :ivar custom_asset_version: CustomAssetVersionOperations operations
    :vartype custom_asset_version: azure_machine_learning_workspaces.aio.operations.CustomAssetVersionOperations
    :ivar data_container: DataContainerOperations operations
    :vartype data_container: azure_machine_learning_workspaces.aio.operations.DataContainerOperations
    :ivar datastore: DatastoreOperations operations
    :vartype datastore: azure_machine_learning_workspaces.aio.operations.DatastoreOperations
    :ivar data_version: DataVersionOperations operations
    :vartype data_version: azure_machine_learning_workspaces.aio.operations.DataVersionOperations
    :ivar environment_container: EnvironmentContainerOperations operations
    :vartype environment_container: azure_machine_learning_workspaces.aio.operations.EnvironmentContainerOperations
    :ivar environment_specification_version: EnvironmentSpecificationVersionOperations operations
    :vartype environment_specification_version: azure_machine_learning_workspaces.aio.operations.EnvironmentSpecificationVersionOperations
    :ivar job: JobOperations operations
    :vartype job: azure_machine_learning_workspaces.aio.operations.JobOperations
    :ivar labeling_job: LabelingJobOperations operations
    :vartype labeling_job: azure_machine_learning_workspaces.aio.operations.LabelingJobOperations
    :ivar model_container: ModelContainerOperations operations
    :vartype model_container: azure_machine_learning_workspaces.aio.operations.ModelContainerOperations
    :ivar model_version: ModelVersionOperations operations
    :vartype model_version: azure_machine_learning_workspaces.aio.operations.ModelVersionOperations
    :ivar online_deployment: OnlineDeploymentOperations operations
    :vartype online_deployment: azure_machine_learning_workspaces.aio.operations.OnlineDeploymentOperations
    :ivar online_endpoint: OnlineEndpointOperations operations
    :vartype online_endpoint: azure_machine_learning_workspaces.aio.operations.OnlineEndpointOperations
    :ivar event: EventOperations operations
    :vartype event: azure_machine_learning_workspaces.aio.operations.EventOperations
    :ivar experiment: ExperimentOperations operations
    :vartype experiment: azure_machine_learning_workspaces.aio.operations.ExperimentOperations
    :ivar run: RunOperations operations
    :vartype run: azure_machine_learning_workspaces.aio.operations.RunOperations
    :ivar run_metric: RunMetricOperations operations
    :vartype run_metric: azure_machine_learning_workspaces.aio.operations.RunMetricOperations
    :ivar run_artifact: RunArtifactOperations operations
    :vartype run_artifact: azure_machine_learning_workspaces.aio.operations.RunArtifactOperations
    :ivar operation: OperationOperations operations
    :vartype operation: azure_machine_learning_workspaces.aio.operations.OperationOperations
    :ivar workspace: WorkspaceOperations operations
    :vartype workspace: azure_machine_learning_workspaces.aio.operations.WorkspaceOperations
    :ivar workspace_feature: WorkspaceFeatureOperations operations
    :vartype workspace_feature: azure_machine_learning_workspaces.aio.operations.WorkspaceFeatureOperations
    :ivar usage: UsageOperations operations
    :vartype usage: azure_machine_learning_workspaces.aio.operations.UsageOperations
    :ivar virtual_machine_size: VirtualMachineSizeOperations operations
    :vartype virtual_machine_size: azure_machine_learning_workspaces.aio.operations.VirtualMachineSizeOperations
    :ivar quota: QuotaOperations operations
    :vartype quota: azure_machine_learning_workspaces.aio.operations.QuotaOperations
    :ivar machine_learning_compute: MachineLearningComputeOperations operations
    :vartype machine_learning_compute: azure_machine_learning_workspaces.aio.operations.MachineLearningComputeOperations
    :ivar sku: SkuOperations operations
    :vartype sku: azure_machine_learning_workspaces.aio.operations.SkuOperations
    :ivar private_endpoint_connection: PrivateEndpointConnectionOperations operations
    :vartype private_endpoint_connection: azure_machine_learning_workspaces.aio.operations.PrivateEndpointConnectionOperations
    :ivar private_link_resource: PrivateLinkResourceOperations operations
    :vartype private_link_resource: azure_machine_learning_workspaces.aio.operations.PrivateLinkResourceOperations
    :ivar linked_workspace: LinkedWorkspaceOperations operations
    :vartype linked_workspace: azure_machine_learning_workspaces.aio.operations.LinkedWorkspaceOperations
    :ivar machine_learning_service: MachineLearningServiceOperations operations
    :vartype machine_learning_service: azure_machine_learning_workspaces.aio.operations.MachineLearningServiceOperations
    :param credential: Credential needed for the client to connect to Azure.
    :type credential: ~azure.core.credentials_async.AsyncTokenCredential
    :param subscription_id: Azure subscription identifier.
    :type subscription_id: str
    :param host: server parameter.
    :type host: str
    :param str base_url: Service URL
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no Retry-After header is present.
    """

    def __init__(
        self,
        credential: "AsyncTokenCredential",
        subscription_id: str,
        host: str = "",
        base_url: Optional[str] = None,
        **kwargs: Any
    ) -> None:
        if not base_url:
            base_url = 'https://management.azure.com'
        self._config = AzureMachineLearningWorkspacesConfiguration(credential, subscription_id, host, **kwargs)
        self._client = AsyncARMPipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.batch_deployment = BatchDeploymentOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.batch_endpoint = BatchEndpointOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.code_container = CodeContainerOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.code_job = CodeJobOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.code_version = CodeVersionOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.custom_asset_container = CustomAssetContainerOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.custom_asset_version = CustomAssetVersionOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.data_container = DataContainerOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.datastore = DatastoreOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.data_version = DataVersionOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.environment_container = EnvironmentContainerOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.environment_specification_version = EnvironmentSpecificationVersionOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.job = JobOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.labeling_job = LabelingJobOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.model_container = ModelContainerOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.model_version = ModelVersionOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.online_deployment = OnlineDeploymentOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.online_endpoint = OnlineEndpointOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.event = EventOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.experiment = ExperimentOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.run = RunOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.run_metric = RunMetricOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.run_artifact = RunArtifactOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.operation = OperationOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.workspace = WorkspaceOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.workspace_feature = WorkspaceFeatureOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.usage = UsageOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.virtual_machine_size = VirtualMachineSizeOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.quota = QuotaOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.machine_learning_compute = MachineLearningComputeOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.sku = SkuOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.private_endpoint_connection = PrivateEndpointConnectionOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.private_link_resource = PrivateLinkResourceOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.linked_workspace = LinkedWorkspaceOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.machine_learning_service = MachineLearningServiceOperations(
            self._client, self._config, self._serialize, self._deserialize)

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> "AzureMachineLearningWorkspaces":
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc_details) -> None:
        await self._client.__aexit__(*exc_details)
