# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AccountKeySection
    from ._models_py3 import AciComputeConfiguration
    from ._models_py3 import AciDeploymentConfiguration
    from ._models_py3 import AciServiceCreateRequest
    from ._models_py3 import AciServiceCreateRequestDataCollection
    from ._models_py3 import AciServiceCreateRequestEncryptionProperties
    from ._models_py3 import AciServiceCreateRequestVnetConfiguration
    from ._models_py3 import AciServiceResponse
    from ._models_py3 import AciServiceResponseDataCollection
    from ._models_py3 import AciServiceResponseEncryptionProperties
    from ._models_py3 import AciServiceResponseEnvironmentImageRequest
    from ._models_py3 import AciServiceResponseVnetConfiguration
    from ._models_py3 import Aks
    from ._models_py3 import AksComputeConfiguration
    from ._models_py3 import AksComputeSecrets
    from ._models_py3 import AksDeploymentConfiguration
    from ._models_py3 import AksNetworkingConfiguration
    from ._models_py3 import AksProperties
    from ._models_py3 import AksReplicaStatus
    from ._models_py3 import AksReplicaStatusError
    from ._models_py3 import AksServiceCreateRequest
    from ._models_py3 import AksServiceCreateRequestAutoScaler
    from ._models_py3 import AksServiceCreateRequestDataCollection
    from ._models_py3 import AksServiceCreateRequestLivenessProbeRequirements
    from ._models_py3 import AksServiceResponse
    from ._models_py3 import AksServiceResponseAutoScaler
    from ._models_py3 import AksServiceResponseDataCollection
    from ._models_py3 import AksServiceResponseDeploymentStatus
    from ._models_py3 import AksServiceResponseEnvironmentImageRequest
    from ._models_py3 import AksServiceResponseLivenessProbeRequirements
    from ._models_py3 import AksVariantResponse
    from ._models_py3 import AmlCompute
    from ._models_py3 import AmlComputeDeploymentConfiguration
    from ._models_py3 import AmlComputeNodeInformation
    from ._models_py3 import AmlComputeNodesInformation
    from ._models_py3 import AmlComputeProperties
    from ._models_py3 import AmlUserFeature
    from ._models_py3 import ArtifactContentInformationDto
    from ._models_py3 import ArtifactDto
    from ._models_py3 import ArtifactPathDto
    from ._models_py3 import AssetContainer
    from ._models_py3 import AssetContainerResource
    from ._models_py3 import AssetContainerResourceArmPaginatedResult
    from ._models_py3 import AssetPath
    from ._models_py3 import AssetReferenceBase
    from ._models_py3 import AuthKeys
    from ._models_py3 import AuthToken
    from ._models_py3 import AutoScaler
    from ._models_py3 import AutomlJob
    from ._models_py3 import AzureDataLakeSection
    from ._models_py3 import AzureMySQLSection
    from ._models_py3 import AzurePostgreSQLSection
    from ._models_py3 import AzureSQLDatabaseSection
    from ._models_py3 import AzureStorageSection
    from ._models_py3 import BanditPolicyConfiguration
    from ._models_py3 import BaseEvent
    from ._models_py3 import BaseEventDto
    from ._models_py3 import BatchAddOrModifyRunRequestDto
    from ._models_py3 import BatchAddOrModifyRunResultDto
    from ._models_py3 import BatchArtifactContentInformationDto
    from ._models_py3 import BatchArtifactCreateCommand
    from ._models_py3 import BatchDeployment
    from ._models_py3 import BatchDeploymentModelReference
    from ._models_py3 import BatchDeploymentResource
    from ._models_py3 import BatchDeploymentSettings
    from ._models_py3 import BatchDeploymentTrackedResource
    from ._models_py3 import BatchDeploymentTrackedResourceArmPaginatedResult
    from ._models_py3 import BatchEndpoint
    from ._models_py3 import BatchEndpointComputeConfiguration
    from ._models_py3 import BatchEndpointResource
    from ._models_py3 import BatchEndpointTrackedResource
    from ._models_py3 import BatchEndpointTrackedResourceArmPaginatedResult
    from ._models_py3 import BatchEventCommandDto
    from ._models_py3 import BatchEventCommandResultDto
    from ._models_py3 import BatchEventCommandResultKvp
    from ._models_py3 import BatchMetricDto
    from ._models_py3 import BatchOutputConfiguration
    from ._models_py3 import BatchPartitioningScheme
    from ._models_py3 import BatchRetrySettings
    from ._models_py3 import CertificateSection
    from ._models_py3 import ClusterUpdateParameters
    from ._models_py3 import CocoExportSummary
    from ._models_py3 import CodeConfiguration
    from ._models_py3 import CodeContainerResource
    from ._models_py3 import CodeContainerResourceArmPaginatedResult
    from ._models_py3 import CodeVersionResource
    from ._models_py3 import CodeVersionResourceArmPaginatedResult
    from ._models_py3 import CommandJob
    from ._models_py3 import CommandJobDistributionConfiguration
    from ._models_py3 import CommandJobResource
    from ._models_py3 import CommandJobResourceArmPaginatedResult
    from ._models_py3 import CommandJobResourceProperties
    from ._models_py3 import Compute
    from ._models_py3 import ComputeBinding
    from ._models_py3 import ComputeConfiguration
    from ._models_py3 import ComputeJobBase
    from ._models_py3 import ComputeNodesInformation
    from ._models_py3 import ComputeResource
    from ._models_py3 import ComputeSecrets
    from ._models_py3 import ContainerRegistry
    from ._models_py3 import ContainerRegistryResponse
    from ._models_py3 import ContainerResourceRequirements
    from ._models_py3 import ContainerResourceRequirementsautogenerated
    from ._models_py3 import CreateEndpointVariantRequest
    from ._models_py3 import CreateRunDto
    from ._models_py3 import CreateServiceRequest
    from ._models_py3 import CreateServiceRequestEnvironmentImageRequest
    from ._models_py3 import CreateServiceRequestKeys
    from ._models_py3 import CreatedByDto
    from ._models_py3 import CreatedFromDto
    from ._models_py3 import CsvExportSummary
    from ._models_py3 import CustomAssetVersionContainerResource
    from ._models_py3 import CustomAssetVersionContainerResourceArmPaginatedResult
    from ._models_py3 import CustomAssetVersionResource
    from ._models_py3 import CustomAssetVersionResourceArmPaginatedResult
    from ._models_py3 import DataBinding
    from ._models_py3 import DataFactory
    from ._models_py3 import DataJob
    from ._models_py3 import DataLakeAnalytics
    from ._models_py3 import DataPathAssetReference
    from ._models_py3 import DataVersionResource
    from ._models_py3 import DataVersionResourceArmPaginatedResult
    from ._models_py3 import Databricks
    from ._models_py3 import DatabricksComputeSecrets
    from ._models_py3 import Dataset
    from ._models_py3 import DatasetExportSummary
    from ._models_py3 import DatasetReference
    from ._models_py3 import DatastoreContents
    from ._models_py3 import DatastoreCredentials
    from ._models_py3 import DatastorePropertiesResource
    from ._models_py3 import DatastorePropertiesResourceArmPaginatedResult
    from ._models_py3 import DebugInfoResponse
    from ._models_py3 import DebugInfoResponseautogenerated
    from ._models_py3 import DeleteExperimentTagsResultDto
    from ._models_py3 import DeleteRunTagsResultDto
    from ._models_py3 import DeleteTagsCommandDto
    from ._models_py3 import DeleteTagsResultDto
    from ._models_py3 import DeploymentConfigurationBase
    from ._models_py3 import DeploymentScaleSettings
    from ._models_py3 import DistributionConfiguration
    from ._models_py3 import DockerProperties
    from ._models_py3 import EarlyTerminationPolicyConfiguration
    from ._models_py3 import EncryptionProperties
    from ._models_py3 import EncryptionPropertiesautogenerated
    from ._models_py3 import EnvironmentContainer
    from ._models_py3 import EnvironmentContainerResource
    from ._models_py3 import EnvironmentContainerResourceArmPaginatedResult
    from ._models_py3 import EnvironmentImageRequest
    from ._models_py3 import EnvironmentImageRequestEnvironment
    from ._models_py3 import EnvironmentImageRequestEnvironmentReference
    from ._models_py3 import EnvironmentImageResponse
    from ._models_py3 import EnvironmentImageResponseEnvironment
    from ._models_py3 import EnvironmentImageResponseEnvironmentReference
    from ._models_py3 import EnvironmentOverrides
    from ._models_py3 import EnvironmentReference
    from ._models_py3 import EnvironmentSpecificationVersion
    from ._models_py3 import EnvironmentSpecificationVersionResource
    from ._models_py3 import EnvironmentSpecificationVersionResourceArmPaginatedResult
    from ._models_py3 import ErrorDetail
    from ._models_py3 import ErrorDetails
    from ._models_py3 import ErrorResponse
    from ._models_py3 import ErrorResponseautogenerated
    from ._models_py3 import ErrorResponseautogenerated2
    from ._models_py3 import EstimatedVmPrice
    from ._models_py3 import EstimatedVmPrices
    from ._models_py3 import EvaluationConfiguration
    from ._models_py3 import ExperimentDto
    from ._models_py3 import ExperimentQueryParamsDto
    from ._models_py3 import ExportSummary
    from ._models_py3 import ExportSummaryResource
    from ._models_py3 import ExportSummaryResourceProperties
    from ._models_py3 import GlusterFsSection
    from ._models_py3 import HdInsight
    from ._models_py3 import IdAssetReference
    from ._models_py3 import ImageAsset
    from ._models_py3 import InferenceEndpointKeys
    from ._models_py3 import InferenceEndpointKeysTrackedResource
    from ._models_py3 import InnerErrorResponse
    from ._models_py3 import InnerErrorResponseautogenerated
    from ._models_py3 import JobBase
    from ._models_py3 import JobBaseInteractionEndpoints
    from ._models_py3 import JobBaseResource
    from ._models_py3 import JobBaseResourceArmPaginatedResult
    from ._models_py3 import JobBaseResourceProperties
    from ._models_py3 import JobOutput
    from ._models_py3 import KeyVaultProperties
    from ._models_py3 import LabelCategory
    from ._models_py3 import LabelClass
    from ._models_py3 import LabelingDatasetConfiguration
    from ._models_py3 import LabelingJob
    from ._models_py3 import LabelingJobImageProperties
    from ._models_py3 import LabelingJobInstructions
    from ._models_py3 import LabelingJobMediaProperties
    from ._models_py3 import LabelingJobMediaPropertiesautogenerated
    from ._models_py3 import LabelingJobResource
    from ._models_py3 import LabelingJobResourceArmPaginatedResult
    from ._models_py3 import LabelingJobTextProperties
    from ._models_py3 import LinkedInfo
    from ._models_py3 import LinkedWorkspace
    from ._models_py3 import LinkedWorkspaceDto
    from ._models_py3 import LinkedWorkspaceProps
    from ._models_py3 import ListAmlUserFeatureResult
    from ._models_py3 import ListUsagesResult
    from ._models_py3 import ListWorkspaceKeysResult
    from ._models_py3 import ListWorkspaceQuotas
    from ._models_py3 import LivenessProbeRequirements
    from ._models_py3 import MachineLearningResource
    from ._models_py3 import MachineLearningServiceError
    from ._models_py3 import MedianStoppingPolicyConfiguration
    from ._models_py3 import MetaApiVersionResponse
    from ._models_py3 import MetricDto
    from ._models_py3 import MetricSchemaDto
    from ._models_py3 import MetricSchemaPropertyDto
    from ._models_py3 import MirComputeConfiguration
    from ._models_py3 import MlAssistConfiguration
    from ._models_py3 import Model
    from ._models_py3 import ModelContainerResource
    from ._models_py3 import ModelContainerResourceArmPaginatedResult
    from ._models_py3 import ModelDataCollection
    from ._models_py3 import ModelDockerSection
    from ._models_py3 import ModelDockerSectionBaseImageRegistry
    from ._models_py3 import ModelDockerSectionResponse
    from ._models_py3 import ModelDockerSectionResponseBaseImageRegistry
    from ._models_py3 import ModelEnvironmentDefinition
    from ._models_py3 import ModelEnvironmentDefinitionDocker
    from ._models_py3 import ModelEnvironmentDefinitionPython
    from ._models_py3 import ModelEnvironmentDefinitionR
    from ._models_py3 import ModelEnvironmentDefinitionResponse
    from ._models_py3 import ModelEnvironmentDefinitionResponseDocker
    from ._models_py3 import ModelEnvironmentDefinitionResponsePython
    from ._models_py3 import ModelEnvironmentDefinitionResponseR
    from ._models_py3 import ModelEnvironmentDefinitionResponseSpark
    from ._models_py3 import ModelEnvironmentDefinitionSpark
    from ._models_py3 import ModelPythonSection
    from ._models_py3 import ModelSparkSection
    from ._models_py3 import ModelVersionResource
    from ._models_py3 import ModelVersionResourceArmPaginatedResult
    from ._models_py3 import ModifyExperimentDto
    from ._models_py3 import ModifyRunDto
    from ._models_py3 import Mpi
    from ._models_py3 import NodeStateCounts
    from ._models_py3 import OnlineDeploymentProperties
    from ._models_py3 import OnlineDeploymentPropertiesDeploymentConfiguration
    from ._models_py3 import OnlineDeploymentPropertiesModelReference
    from ._models_py3 import OnlineDeploymentPropertiesTrackedResource
    from ._models_py3 import OnlineDeploymentPropertiesTrackedResourceArmPaginatedResult
    from ._models_py3 import OnlineEndpointProperties
    from ._models_py3 import OnlineEndpointPropertiesComputeConfiguration
    from ._models_py3 import OnlineEndpointPropertiesTrackedResource
    from ._models_py3 import OnlineEndpointPropertiesTrackedResourceArmPaginatedResult
    from ._models_py3 import Operation
    from ._models_py3 import OperationDisplay
    from ._models_py3 import OperationListResult
    from ._models_py3 import OutputDatasetLineage
    from ._models_py3 import OutputPathAssetReference
    from ._models_py3 import PaginatedArtifactContentInformationDto
    from ._models_py3 import PaginatedArtifactDto
    from ._models_py3 import PaginatedBaseEvent
    from ._models_py3 import PaginatedComputeResourcesList
    from ._models_py3 import PaginatedExperimentDto
    from ._models_py3 import PaginatedLinkedWorkspaceList
    from ._models_py3 import PaginatedRunDto
    from ._models_py3 import PaginatedRunMetricDto
    from ._models_py3 import PaginatedServiceList
    from ._models_py3 import ParameterSamplingConfiguration
    from ._models_py3 import Password
    from ._models_py3 import PipelineJob
    from ._models_py3 import PrivateEndpoint
    from ._models_py3 import PrivateEndpointConnection
    from ._models_py3 import PrivateLinkResource
    from ._models_py3 import PrivateLinkResourceListResult
    from ._models_py3 import PrivateLinkServiceConnectionState
    from ._models_py3 import ProgressMetrics
    from ._models_py3 import PyTorch
    from ._models_py3 import PythonProperties
    from ._models_py3 import QueryParamsDto
    from ._models_py3 import QueueingInfoDto
    from ._models_py3 import QuotaBaseProperties
    from ._models_py3 import QuotaUpdateParameters
    from ._models_py3 import RCranPackage
    from ._models_py3 import RGitHubPackage
    from ._models_py3 import RGitHubPackageResponse
    from ._models_py3 import RSection
    from ._models_py3 import RSectionResponse
    from ._models_py3 import RegenerateEndpointKeysRequest
    from ._models_py3 import RegistryListCredentialsResult
    from ._models_py3 import ResourceId
    from ._models_py3 import ResourceIdentityInArm
    from ._models_py3 import ResourceName
    from ._models_py3 import ResourceQuota
    from ._models_py3 import ResourceSkuLocationInfo
    from ._models_py3 import ResourceSkuZoneDetails
    from ._models_py3 import Restriction
    from ._models_py3 import RootError
    from ._models_py3 import RootErrorautogenerated
    from ._models_py3 import RunCountsDto
    from ._models_py3 import RunDetailsDto
    from ._models_py3 import RunDetailsWarningDto
    from ._models_py3 import RunDto
    from ._models_py3 import RunMetricDto
    from ._models_py3 import RunOptions
    from ._models_py3 import SQLAdminSection
    from ._models_py3 import SSLConfiguration
    from ._models_py3 import SSLConfigurationautogenerated
    from ._models_py3 import SasSection
    from ._models_py3 import ScaleSettings
    from ._models_py3 import ScaleSettingsautogenerated
    from ._models_py3 import ServicePrincipalCredentials
    from ._models_py3 import ServicePrincipalSection
    from ._models_py3 import ServiceResource
    from ._models_py3 import ServiceResponseBase
    from ._models_py3 import ServiceResponseBaseError
    from ._models_py3 import SharedPrivateLinkResource
    from ._models_py3 import Sku
    from ._models_py3 import SkuCapability
    from ._models_py3 import SkuListResult
    from ._models_py3 import SparkMavenPackage
    from ._models_py3 import StatusMessage
    from ._models_py3 import SweepJob
    from ._models_py3 import SystemData
    from ._models_py3 import SystemService
    from ._models_py3 import Tensorflow
    from ._models_py3 import TerminationConfiguration
    from ._models_py3 import TerminationConfigurationEarlyTerminationPolicyConfiguration
    from ._models_py3 import TokenResult
    from ._models_py3 import TrialJob
    from ._models_py3 import TruncationSelectionPolicyConfiguration
    from ._models_py3 import UpdateWorkspaceQuotas
    from ._models_py3 import UpdateWorkspaceQuotasResult
    from ._models_py3 import Usage
    from ._models_py3 import UsageName
    from ._models_py3 import UserAccountCredentials
    from ._models_py3 import UserAssignedIdentity
    from ._models_py3 import UserAssignedIdentityMeta
    from ._models_py3 import VirtualMachine
    from ._models_py3 import VirtualMachineImage
    from ._models_py3 import VirtualMachineSecrets
    from ._models_py3 import VirtualMachineSize
    from ._models_py3 import VirtualMachineSizeListResult
    from ._models_py3 import VirtualMachineSshCredentials
    from ._models_py3 import VnetConfiguration
    from ._models_py3 import VnetConfigurationautogenerated
    from ._models_py3 import Workspace
    from ._models_py3 import WorkspaceListResult
    from ._models_py3 import WorkspaceSku
    from ._models_py3 import WorkspaceUpdateParameters
except (SyntaxError, ImportError):
    from ._models import AccountKeySection  # type: ignore
    from ._models import AciComputeConfiguration  # type: ignore
    from ._models import AciDeploymentConfiguration  # type: ignore
    from ._models import AciServiceCreateRequest  # type: ignore
    from ._models import AciServiceCreateRequestDataCollection  # type: ignore
    from ._models import AciServiceCreateRequestEncryptionProperties  # type: ignore
    from ._models import AciServiceCreateRequestVnetConfiguration  # type: ignore
    from ._models import AciServiceResponse  # type: ignore
    from ._models import AciServiceResponseDataCollection  # type: ignore
    from ._models import AciServiceResponseEncryptionProperties  # type: ignore
    from ._models import AciServiceResponseEnvironmentImageRequest  # type: ignore
    from ._models import AciServiceResponseVnetConfiguration  # type: ignore
    from ._models import Aks  # type: ignore
    from ._models import AksComputeConfiguration  # type: ignore
    from ._models import AksComputeSecrets  # type: ignore
    from ._models import AksDeploymentConfiguration  # type: ignore
    from ._models import AksNetworkingConfiguration  # type: ignore
    from ._models import AksProperties  # type: ignore
    from ._models import AksReplicaStatus  # type: ignore
    from ._models import AksReplicaStatusError  # type: ignore
    from ._models import AksServiceCreateRequest  # type: ignore
    from ._models import AksServiceCreateRequestAutoScaler  # type: ignore
    from ._models import AksServiceCreateRequestDataCollection  # type: ignore
    from ._models import AksServiceCreateRequestLivenessProbeRequirements  # type: ignore
    from ._models import AksServiceResponse  # type: ignore
    from ._models import AksServiceResponseAutoScaler  # type: ignore
    from ._models import AksServiceResponseDataCollection  # type: ignore
    from ._models import AksServiceResponseDeploymentStatus  # type: ignore
    from ._models import AksServiceResponseEnvironmentImageRequest  # type: ignore
    from ._models import AksServiceResponseLivenessProbeRequirements  # type: ignore
    from ._models import AksVariantResponse  # type: ignore
    from ._models import AmlCompute  # type: ignore
    from ._models import AmlComputeDeploymentConfiguration  # type: ignore
    from ._models import AmlComputeNodeInformation  # type: ignore
    from ._models import AmlComputeNodesInformation  # type: ignore
    from ._models import AmlComputeProperties  # type: ignore
    from ._models import AmlUserFeature  # type: ignore
    from ._models import ArtifactContentInformationDto  # type: ignore
    from ._models import ArtifactDto  # type: ignore
    from ._models import ArtifactPathDto  # type: ignore
    from ._models import AssetContainer  # type: ignore
    from ._models import AssetContainerResource  # type: ignore
    from ._models import AssetContainerResourceArmPaginatedResult  # type: ignore
    from ._models import AssetPath  # type: ignore
    from ._models import AssetReferenceBase  # type: ignore
    from ._models import AuthKeys  # type: ignore
    from ._models import AuthToken  # type: ignore
    from ._models import AutoScaler  # type: ignore
    from ._models import AutomlJob  # type: ignore
    from ._models import AzureDataLakeSection  # type: ignore
    from ._models import AzureMySQLSection  # type: ignore
    from ._models import AzurePostgreSQLSection  # type: ignore
    from ._models import AzureSQLDatabaseSection  # type: ignore
    from ._models import AzureStorageSection  # type: ignore
    from ._models import BanditPolicyConfiguration  # type: ignore
    from ._models import BaseEvent  # type: ignore
    from ._models import BaseEventDto  # type: ignore
    from ._models import BatchAddOrModifyRunRequestDto  # type: ignore
    from ._models import BatchAddOrModifyRunResultDto  # type: ignore
    from ._models import BatchArtifactContentInformationDto  # type: ignore
    from ._models import BatchArtifactCreateCommand  # type: ignore
    from ._models import BatchDeployment  # type: ignore
    from ._models import BatchDeploymentModelReference  # type: ignore
    from ._models import BatchDeploymentResource  # type: ignore
    from ._models import BatchDeploymentSettings  # type: ignore
    from ._models import BatchDeploymentTrackedResource  # type: ignore
    from ._models import BatchDeploymentTrackedResourceArmPaginatedResult  # type: ignore
    from ._models import BatchEndpoint  # type: ignore
    from ._models import BatchEndpointComputeConfiguration  # type: ignore
    from ._models import BatchEndpointResource  # type: ignore
    from ._models import BatchEndpointTrackedResource  # type: ignore
    from ._models import BatchEndpointTrackedResourceArmPaginatedResult  # type: ignore
    from ._models import BatchEventCommandDto  # type: ignore
    from ._models import BatchEventCommandResultDto  # type: ignore
    from ._models import BatchEventCommandResultKvp  # type: ignore
    from ._models import BatchMetricDto  # type: ignore
    from ._models import BatchOutputConfiguration  # type: ignore
    from ._models import BatchPartitioningScheme  # type: ignore
    from ._models import BatchRetrySettings  # type: ignore
    from ._models import CertificateSection  # type: ignore
    from ._models import ClusterUpdateParameters  # type: ignore
    from ._models import CocoExportSummary  # type: ignore
    from ._models import CodeConfiguration  # type: ignore
    from ._models import CodeContainerResource  # type: ignore
    from ._models import CodeContainerResourceArmPaginatedResult  # type: ignore
    from ._models import CodeVersionResource  # type: ignore
    from ._models import CodeVersionResourceArmPaginatedResult  # type: ignore
    from ._models import CommandJob  # type: ignore
    from ._models import CommandJobDistributionConfiguration  # type: ignore
    from ._models import CommandJobResource  # type: ignore
    from ._models import CommandJobResourceArmPaginatedResult  # type: ignore
    from ._models import CommandJobResourceProperties  # type: ignore
    from ._models import Compute  # type: ignore
    from ._models import ComputeBinding  # type: ignore
    from ._models import ComputeConfiguration  # type: ignore
    from ._models import ComputeJobBase  # type: ignore
    from ._models import ComputeNodesInformation  # type: ignore
    from ._models import ComputeResource  # type: ignore
    from ._models import ComputeSecrets  # type: ignore
    from ._models import ContainerRegistry  # type: ignore
    from ._models import ContainerRegistryResponse  # type: ignore
    from ._models import ContainerResourceRequirements  # type: ignore
    from ._models import ContainerResourceRequirementsautogenerated  # type: ignore
    from ._models import CreateEndpointVariantRequest  # type: ignore
    from ._models import CreateRunDto  # type: ignore
    from ._models import CreateServiceRequest  # type: ignore
    from ._models import CreateServiceRequestEnvironmentImageRequest  # type: ignore
    from ._models import CreateServiceRequestKeys  # type: ignore
    from ._models import CreatedByDto  # type: ignore
    from ._models import CreatedFromDto  # type: ignore
    from ._models import CsvExportSummary  # type: ignore
    from ._models import CustomAssetVersionContainerResource  # type: ignore
    from ._models import CustomAssetVersionContainerResourceArmPaginatedResult  # type: ignore
    from ._models import CustomAssetVersionResource  # type: ignore
    from ._models import CustomAssetVersionResourceArmPaginatedResult  # type: ignore
    from ._models import DataBinding  # type: ignore
    from ._models import DataFactory  # type: ignore
    from ._models import DataJob  # type: ignore
    from ._models import DataLakeAnalytics  # type: ignore
    from ._models import DataPathAssetReference  # type: ignore
    from ._models import DataVersionResource  # type: ignore
    from ._models import DataVersionResourceArmPaginatedResult  # type: ignore
    from ._models import Databricks  # type: ignore
    from ._models import DatabricksComputeSecrets  # type: ignore
    from ._models import Dataset  # type: ignore
    from ._models import DatasetExportSummary  # type: ignore
    from ._models import DatasetReference  # type: ignore
    from ._models import DatastoreContents  # type: ignore
    from ._models import DatastoreCredentials  # type: ignore
    from ._models import DatastorePropertiesResource  # type: ignore
    from ._models import DatastorePropertiesResourceArmPaginatedResult  # type: ignore
    from ._models import DebugInfoResponse  # type: ignore
    from ._models import DebugInfoResponseautogenerated  # type: ignore
    from ._models import DeleteExperimentTagsResultDto  # type: ignore
    from ._models import DeleteRunTagsResultDto  # type: ignore
    from ._models import DeleteTagsCommandDto  # type: ignore
    from ._models import DeleteTagsResultDto  # type: ignore
    from ._models import DeploymentConfigurationBase  # type: ignore
    from ._models import DeploymentScaleSettings  # type: ignore
    from ._models import DistributionConfiguration  # type: ignore
    from ._models import DockerProperties  # type: ignore
    from ._models import EarlyTerminationPolicyConfiguration  # type: ignore
    from ._models import EncryptionProperties  # type: ignore
    from ._models import EncryptionPropertiesautogenerated  # type: ignore
    from ._models import EnvironmentContainer  # type: ignore
    from ._models import EnvironmentContainerResource  # type: ignore
    from ._models import EnvironmentContainerResourceArmPaginatedResult  # type: ignore
    from ._models import EnvironmentImageRequest  # type: ignore
    from ._models import EnvironmentImageRequestEnvironment  # type: ignore
    from ._models import EnvironmentImageRequestEnvironmentReference  # type: ignore
    from ._models import EnvironmentImageResponse  # type: ignore
    from ._models import EnvironmentImageResponseEnvironment  # type: ignore
    from ._models import EnvironmentImageResponseEnvironmentReference  # type: ignore
    from ._models import EnvironmentOverrides  # type: ignore
    from ._models import EnvironmentReference  # type: ignore
    from ._models import EnvironmentSpecificationVersion  # type: ignore
    from ._models import EnvironmentSpecificationVersionResource  # type: ignore
    from ._models import EnvironmentSpecificationVersionResourceArmPaginatedResult  # type: ignore
    from ._models import ErrorDetail  # type: ignore
    from ._models import ErrorDetails  # type: ignore
    from ._models import ErrorResponse  # type: ignore
    from ._models import ErrorResponseautogenerated  # type: ignore
    from ._models import ErrorResponseautogenerated2  # type: ignore
    from ._models import EstimatedVmPrice  # type: ignore
    from ._models import EstimatedVmPrices  # type: ignore
    from ._models import EvaluationConfiguration  # type: ignore
    from ._models import ExperimentDto  # type: ignore
    from ._models import ExperimentQueryParamsDto  # type: ignore
    from ._models import ExportSummary  # type: ignore
    from ._models import ExportSummaryResource  # type: ignore
    from ._models import ExportSummaryResourceProperties  # type: ignore
    from ._models import GlusterFsSection  # type: ignore
    from ._models import HdInsight  # type: ignore
    from ._models import IdAssetReference  # type: ignore
    from ._models import ImageAsset  # type: ignore
    from ._models import InferenceEndpointKeys  # type: ignore
    from ._models import InferenceEndpointKeysTrackedResource  # type: ignore
    from ._models import InnerErrorResponse  # type: ignore
    from ._models import InnerErrorResponseautogenerated  # type: ignore
    from ._models import JobBase  # type: ignore
    from ._models import JobBaseInteractionEndpoints  # type: ignore
    from ._models import JobBaseResource  # type: ignore
    from ._models import JobBaseResourceArmPaginatedResult  # type: ignore
    from ._models import JobBaseResourceProperties  # type: ignore
    from ._models import JobOutput  # type: ignore
    from ._models import KeyVaultProperties  # type: ignore
    from ._models import LabelCategory  # type: ignore
    from ._models import LabelClass  # type: ignore
    from ._models import LabelingDatasetConfiguration  # type: ignore
    from ._models import LabelingJob  # type: ignore
    from ._models import LabelingJobImageProperties  # type: ignore
    from ._models import LabelingJobInstructions  # type: ignore
    from ._models import LabelingJobMediaProperties  # type: ignore
    from ._models import LabelingJobMediaPropertiesautogenerated  # type: ignore
    from ._models import LabelingJobResource  # type: ignore
    from ._models import LabelingJobResourceArmPaginatedResult  # type: ignore
    from ._models import LabelingJobTextProperties  # type: ignore
    from ._models import LinkedInfo  # type: ignore
    from ._models import LinkedWorkspace  # type: ignore
    from ._models import LinkedWorkspaceDto  # type: ignore
    from ._models import LinkedWorkspaceProps  # type: ignore
    from ._models import ListAmlUserFeatureResult  # type: ignore
    from ._models import ListUsagesResult  # type: ignore
    from ._models import ListWorkspaceKeysResult  # type: ignore
    from ._models import ListWorkspaceQuotas  # type: ignore
    from ._models import LivenessProbeRequirements  # type: ignore
    from ._models import MachineLearningResource  # type: ignore
    from ._models import MachineLearningServiceError  # type: ignore
    from ._models import MedianStoppingPolicyConfiguration  # type: ignore
    from ._models import MetaApiVersionResponse  # type: ignore
    from ._models import MetricDto  # type: ignore
    from ._models import MetricSchemaDto  # type: ignore
    from ._models import MetricSchemaPropertyDto  # type: ignore
    from ._models import MirComputeConfiguration  # type: ignore
    from ._models import MlAssistConfiguration  # type: ignore
    from ._models import Model  # type: ignore
    from ._models import ModelContainerResource  # type: ignore
    from ._models import ModelContainerResourceArmPaginatedResult  # type: ignore
    from ._models import ModelDataCollection  # type: ignore
    from ._models import ModelDockerSection  # type: ignore
    from ._models import ModelDockerSectionBaseImageRegistry  # type: ignore
    from ._models import ModelDockerSectionResponse  # type: ignore
    from ._models import ModelDockerSectionResponseBaseImageRegistry  # type: ignore
    from ._models import ModelEnvironmentDefinition  # type: ignore
    from ._models import ModelEnvironmentDefinitionDocker  # type: ignore
    from ._models import ModelEnvironmentDefinitionPython  # type: ignore
    from ._models import ModelEnvironmentDefinitionR  # type: ignore
    from ._models import ModelEnvironmentDefinitionResponse  # type: ignore
    from ._models import ModelEnvironmentDefinitionResponseDocker  # type: ignore
    from ._models import ModelEnvironmentDefinitionResponsePython  # type: ignore
    from ._models import ModelEnvironmentDefinitionResponseR  # type: ignore
    from ._models import ModelEnvironmentDefinitionResponseSpark  # type: ignore
    from ._models import ModelEnvironmentDefinitionSpark  # type: ignore
    from ._models import ModelPythonSection  # type: ignore
    from ._models import ModelSparkSection  # type: ignore
    from ._models import ModelVersionResource  # type: ignore
    from ._models import ModelVersionResourceArmPaginatedResult  # type: ignore
    from ._models import ModifyExperimentDto  # type: ignore
    from ._models import ModifyRunDto  # type: ignore
    from ._models import Mpi  # type: ignore
    from ._models import NodeStateCounts  # type: ignore
    from ._models import OnlineDeploymentProperties  # type: ignore
    from ._models import OnlineDeploymentPropertiesDeploymentConfiguration  # type: ignore
    from ._models import OnlineDeploymentPropertiesModelReference  # type: ignore
    from ._models import OnlineDeploymentPropertiesTrackedResource  # type: ignore
    from ._models import OnlineDeploymentPropertiesTrackedResourceArmPaginatedResult  # type: ignore
    from ._models import OnlineEndpointProperties  # type: ignore
    from ._models import OnlineEndpointPropertiesComputeConfiguration  # type: ignore
    from ._models import OnlineEndpointPropertiesTrackedResource  # type: ignore
    from ._models import OnlineEndpointPropertiesTrackedResourceArmPaginatedResult  # type: ignore
    from ._models import Operation  # type: ignore
    from ._models import OperationDisplay  # type: ignore
    from ._models import OperationListResult  # type: ignore
    from ._models import OutputDatasetLineage  # type: ignore
    from ._models import OutputPathAssetReference  # type: ignore
    from ._models import PaginatedArtifactContentInformationDto  # type: ignore
    from ._models import PaginatedArtifactDto  # type: ignore
    from ._models import PaginatedBaseEvent  # type: ignore
    from ._models import PaginatedComputeResourcesList  # type: ignore
    from ._models import PaginatedExperimentDto  # type: ignore
    from ._models import PaginatedLinkedWorkspaceList  # type: ignore
    from ._models import PaginatedRunDto  # type: ignore
    from ._models import PaginatedRunMetricDto  # type: ignore
    from ._models import PaginatedServiceList  # type: ignore
    from ._models import ParameterSamplingConfiguration  # type: ignore
    from ._models import Password  # type: ignore
    from ._models import PipelineJob  # type: ignore
    from ._models import PrivateEndpoint  # type: ignore
    from ._models import PrivateEndpointConnection  # type: ignore
    from ._models import PrivateLinkResource  # type: ignore
    from ._models import PrivateLinkResourceListResult  # type: ignore
    from ._models import PrivateLinkServiceConnectionState  # type: ignore
    from ._models import ProgressMetrics  # type: ignore
    from ._models import PyTorch  # type: ignore
    from ._models import PythonProperties  # type: ignore
    from ._models import QueryParamsDto  # type: ignore
    from ._models import QueueingInfoDto  # type: ignore
    from ._models import QuotaBaseProperties  # type: ignore
    from ._models import QuotaUpdateParameters  # type: ignore
    from ._models import RCranPackage  # type: ignore
    from ._models import RGitHubPackage  # type: ignore
    from ._models import RGitHubPackageResponse  # type: ignore
    from ._models import RSection  # type: ignore
    from ._models import RSectionResponse  # type: ignore
    from ._models import RegenerateEndpointKeysRequest  # type: ignore
    from ._models import RegistryListCredentialsResult  # type: ignore
    from ._models import ResourceId  # type: ignore
    from ._models import ResourceIdentityInArm  # type: ignore
    from ._models import ResourceName  # type: ignore
    from ._models import ResourceQuota  # type: ignore
    from ._models import ResourceSkuLocationInfo  # type: ignore
    from ._models import ResourceSkuZoneDetails  # type: ignore
    from ._models import Restriction  # type: ignore
    from ._models import RootError  # type: ignore
    from ._models import RootErrorautogenerated  # type: ignore
    from ._models import RunCountsDto  # type: ignore
    from ._models import RunDetailsDto  # type: ignore
    from ._models import RunDetailsWarningDto  # type: ignore
    from ._models import RunDto  # type: ignore
    from ._models import RunMetricDto  # type: ignore
    from ._models import RunOptions  # type: ignore
    from ._models import SQLAdminSection  # type: ignore
    from ._models import SSLConfiguration  # type: ignore
    from ._models import SSLConfigurationautogenerated  # type: ignore
    from ._models import SasSection  # type: ignore
    from ._models import ScaleSettings  # type: ignore
    from ._models import ScaleSettingsautogenerated  # type: ignore
    from ._models import ServicePrincipalCredentials  # type: ignore
    from ._models import ServicePrincipalSection  # type: ignore
    from ._models import ServiceResource  # type: ignore
    from ._models import ServiceResponseBase  # type: ignore
    from ._models import ServiceResponseBaseError  # type: ignore
    from ._models import SharedPrivateLinkResource  # type: ignore
    from ._models import Sku  # type: ignore
    from ._models import SkuCapability  # type: ignore
    from ._models import SkuListResult  # type: ignore
    from ._models import SparkMavenPackage  # type: ignore
    from ._models import StatusMessage  # type: ignore
    from ._models import SweepJob  # type: ignore
    from ._models import SystemData  # type: ignore
    from ._models import SystemService  # type: ignore
    from ._models import Tensorflow  # type: ignore
    from ._models import TerminationConfiguration  # type: ignore
    from ._models import TerminationConfigurationEarlyTerminationPolicyConfiguration  # type: ignore
    from ._models import TokenResult  # type: ignore
    from ._models import TrialJob  # type: ignore
    from ._models import TruncationSelectionPolicyConfiguration  # type: ignore
    from ._models import UpdateWorkspaceQuotas  # type: ignore
    from ._models import UpdateWorkspaceQuotasResult  # type: ignore
    from ._models import Usage  # type: ignore
    from ._models import UsageName  # type: ignore
    from ._models import UserAccountCredentials  # type: ignore
    from ._models import UserAssignedIdentity  # type: ignore
    from ._models import UserAssignedIdentityMeta  # type: ignore
    from ._models import VirtualMachine  # type: ignore
    from ._models import VirtualMachineImage  # type: ignore
    from ._models import VirtualMachineSecrets  # type: ignore
    from ._models import VirtualMachineSize  # type: ignore
    from ._models import VirtualMachineSizeListResult  # type: ignore
    from ._models import VirtualMachineSshCredentials  # type: ignore
    from ._models import VnetConfiguration  # type: ignore
    from ._models import VnetConfigurationautogenerated  # type: ignore
    from ._models import Workspace  # type: ignore
    from ._models import WorkspaceListResult  # type: ignore
    from ._models import WorkspaceSku  # type: ignore
    from ._models import WorkspaceUpdateParameters  # type: ignore

from ._azure_machine_learning_workspaces_enums import (
    AcquisitionFunction,
    AllocationState,
    BatchLoggingLevel,
    BatchOutputAction,
    BillingCurrency,
    CommunicationBackend,
    ComputeEnvironmentType,
    ComputeType,
    ContentsType,
    CredentialsType,
    CustomAssetType,
    DataBindingMode,
    DatasetConsumptionType,
    DatasetDeliveryMechanism,
    DatasetOutputMechanism,
    DatasetOutputType,
    DatasetType,
    DeploymentProvisioningState,
    DeploymentType,
    DistributionType,
    DockerSpecificationType,
    EarlyTerminationPolicyType,
    EncryptionStatus,
    EndpointAuthModeType,
    EndpointProvisioningState,
    Enum0,
    Enum2,
    Enum3,
    Enum4,
    Enum5,
    EnvironmentSpecificationType,
    ExperimentQueryParamsDtoViewType,
    ExportFormatType,
    FlowType,
    ImageAnnotationType,
    JobStatus,
    JobType,
    KeyType,
    LabelExportState,
    MediaType,
    NodeState,
    OptimizationMetric,
    OrderString,
    OsType,
    ParameterSamplingType,
    PrimaryMetricGoal,
    PrivateEndpointConnectionProvisioningState,
    PrivateEndpointServiceConnectionStatus,
    ProvisioningState,
    PythonSpecificationType,
    QuotaUnit,
    ReasonCode,
    ReferenceType,
    RemoteLoginPortPublicAccess,
    ResourceIdentityType,
    SSLConfigurationStatus,
    ScaleTypeMode,
    Status,
    StatusMessageLevel,
    TrainingType,
    UnderlyingResourceAction,
    UnitOfMeasure,
    UsageUnit,
    UserType,
    VariantType,
    VmPriceOsType,
    VmPriority,
    VmTier,
    WebServiceState,
)

__all__ = [
    'AccountKeySection',
    'AciComputeConfiguration',
    'AciDeploymentConfiguration',
    'AciServiceCreateRequest',
    'AciServiceCreateRequestDataCollection',
    'AciServiceCreateRequestEncryptionProperties',
    'AciServiceCreateRequestVnetConfiguration',
    'AciServiceResponse',
    'AciServiceResponseDataCollection',
    'AciServiceResponseEncryptionProperties',
    'AciServiceResponseEnvironmentImageRequest',
    'AciServiceResponseVnetConfiguration',
    'Aks',
    'AksComputeConfiguration',
    'AksComputeSecrets',
    'AksDeploymentConfiguration',
    'AksNetworkingConfiguration',
    'AksProperties',
    'AksReplicaStatus',
    'AksReplicaStatusError',
    'AksServiceCreateRequest',
    'AksServiceCreateRequestAutoScaler',
    'AksServiceCreateRequestDataCollection',
    'AksServiceCreateRequestLivenessProbeRequirements',
    'AksServiceResponse',
    'AksServiceResponseAutoScaler',
    'AksServiceResponseDataCollection',
    'AksServiceResponseDeploymentStatus',
    'AksServiceResponseEnvironmentImageRequest',
    'AksServiceResponseLivenessProbeRequirements',
    'AksVariantResponse',
    'AmlCompute',
    'AmlComputeDeploymentConfiguration',
    'AmlComputeNodeInformation',
    'AmlComputeNodesInformation',
    'AmlComputeProperties',
    'AmlUserFeature',
    'ArtifactContentInformationDto',
    'ArtifactDto',
    'ArtifactPathDto',
    'AssetContainer',
    'AssetContainerResource',
    'AssetContainerResourceArmPaginatedResult',
    'AssetPath',
    'AssetReferenceBase',
    'AuthKeys',
    'AuthToken',
    'AutoScaler',
    'AutomlJob',
    'AzureDataLakeSection',
    'AzureMySQLSection',
    'AzurePostgreSQLSection',
    'AzureSQLDatabaseSection',
    'AzureStorageSection',
    'BanditPolicyConfiguration',
    'BaseEvent',
    'BaseEventDto',
    'BatchAddOrModifyRunRequestDto',
    'BatchAddOrModifyRunResultDto',
    'BatchArtifactContentInformationDto',
    'BatchArtifactCreateCommand',
    'BatchDeployment',
    'BatchDeploymentModelReference',
    'BatchDeploymentResource',
    'BatchDeploymentSettings',
    'BatchDeploymentTrackedResource',
    'BatchDeploymentTrackedResourceArmPaginatedResult',
    'BatchEndpoint',
    'BatchEndpointComputeConfiguration',
    'BatchEndpointResource',
    'BatchEndpointTrackedResource',
    'BatchEndpointTrackedResourceArmPaginatedResult',
    'BatchEventCommandDto',
    'BatchEventCommandResultDto',
    'BatchEventCommandResultKvp',
    'BatchMetricDto',
    'BatchOutputConfiguration',
    'BatchPartitioningScheme',
    'BatchRetrySettings',
    'CertificateSection',
    'ClusterUpdateParameters',
    'CocoExportSummary',
    'CodeConfiguration',
    'CodeContainerResource',
    'CodeContainerResourceArmPaginatedResult',
    'CodeVersionResource',
    'CodeVersionResourceArmPaginatedResult',
    'CommandJob',
    'CommandJobDistributionConfiguration',
    'CommandJobResource',
    'CommandJobResourceArmPaginatedResult',
    'CommandJobResourceProperties',
    'Compute',
    'ComputeBinding',
    'ComputeConfiguration',
    'ComputeJobBase',
    'ComputeNodesInformation',
    'ComputeResource',
    'ComputeSecrets',
    'ContainerRegistry',
    'ContainerRegistryResponse',
    'ContainerResourceRequirements',
    'ContainerResourceRequirementsautogenerated',
    'CreateEndpointVariantRequest',
    'CreateRunDto',
    'CreateServiceRequest',
    'CreateServiceRequestEnvironmentImageRequest',
    'CreateServiceRequestKeys',
    'CreatedByDto',
    'CreatedFromDto',
    'CsvExportSummary',
    'CustomAssetVersionContainerResource',
    'CustomAssetVersionContainerResourceArmPaginatedResult',
    'CustomAssetVersionResource',
    'CustomAssetVersionResourceArmPaginatedResult',
    'DataBinding',
    'DataFactory',
    'DataJob',
    'DataLakeAnalytics',
    'DataPathAssetReference',
    'DataVersionResource',
    'DataVersionResourceArmPaginatedResult',
    'Databricks',
    'DatabricksComputeSecrets',
    'Dataset',
    'DatasetExportSummary',
    'DatasetReference',
    'DatastoreContents',
    'DatastoreCredentials',
    'DatastorePropertiesResource',
    'DatastorePropertiesResourceArmPaginatedResult',
    'DebugInfoResponse',
    'DebugInfoResponseautogenerated',
    'DeleteExperimentTagsResultDto',
    'DeleteRunTagsResultDto',
    'DeleteTagsCommandDto',
    'DeleteTagsResultDto',
    'DeploymentConfigurationBase',
    'DeploymentScaleSettings',
    'DistributionConfiguration',
    'DockerProperties',
    'EarlyTerminationPolicyConfiguration',
    'EncryptionProperties',
    'EncryptionPropertiesautogenerated',
    'EnvironmentContainer',
    'EnvironmentContainerResource',
    'EnvironmentContainerResourceArmPaginatedResult',
    'EnvironmentImageRequest',
    'EnvironmentImageRequestEnvironment',
    'EnvironmentImageRequestEnvironmentReference',
    'EnvironmentImageResponse',
    'EnvironmentImageResponseEnvironment',
    'EnvironmentImageResponseEnvironmentReference',
    'EnvironmentOverrides',
    'EnvironmentReference',
    'EnvironmentSpecificationVersion',
    'EnvironmentSpecificationVersionResource',
    'EnvironmentSpecificationVersionResourceArmPaginatedResult',
    'ErrorDetail',
    'ErrorDetails',
    'ErrorResponse',
    'ErrorResponseautogenerated',
    'ErrorResponseautogenerated2',
    'EstimatedVmPrice',
    'EstimatedVmPrices',
    'EvaluationConfiguration',
    'ExperimentDto',
    'ExperimentQueryParamsDto',
    'ExportSummary',
    'ExportSummaryResource',
    'ExportSummaryResourceProperties',
    'GlusterFsSection',
    'HdInsight',
    'IdAssetReference',
    'ImageAsset',
    'InferenceEndpointKeys',
    'InferenceEndpointKeysTrackedResource',
    'InnerErrorResponse',
    'InnerErrorResponseautogenerated',
    'JobBase',
    'JobBaseInteractionEndpoints',
    'JobBaseResource',
    'JobBaseResourceArmPaginatedResult',
    'JobBaseResourceProperties',
    'JobOutput',
    'KeyVaultProperties',
    'LabelCategory',
    'LabelClass',
    'LabelingDatasetConfiguration',
    'LabelingJob',
    'LabelingJobImageProperties',
    'LabelingJobInstructions',
    'LabelingJobMediaProperties',
    'LabelingJobMediaPropertiesautogenerated',
    'LabelingJobResource',
    'LabelingJobResourceArmPaginatedResult',
    'LabelingJobTextProperties',
    'LinkedInfo',
    'LinkedWorkspace',
    'LinkedWorkspaceDto',
    'LinkedWorkspaceProps',
    'ListAmlUserFeatureResult',
    'ListUsagesResult',
    'ListWorkspaceKeysResult',
    'ListWorkspaceQuotas',
    'LivenessProbeRequirements',
    'MachineLearningResource',
    'MachineLearningServiceError',
    'MedianStoppingPolicyConfiguration',
    'MetaApiVersionResponse',
    'MetricDto',
    'MetricSchemaDto',
    'MetricSchemaPropertyDto',
    'MirComputeConfiguration',
    'MlAssistConfiguration',
    'Model',
    'ModelContainerResource',
    'ModelContainerResourceArmPaginatedResult',
    'ModelDataCollection',
    'ModelDockerSection',
    'ModelDockerSectionBaseImageRegistry',
    'ModelDockerSectionResponse',
    'ModelDockerSectionResponseBaseImageRegistry',
    'ModelEnvironmentDefinition',
    'ModelEnvironmentDefinitionDocker',
    'ModelEnvironmentDefinitionPython',
    'ModelEnvironmentDefinitionR',
    'ModelEnvironmentDefinitionResponse',
    'ModelEnvironmentDefinitionResponseDocker',
    'ModelEnvironmentDefinitionResponsePython',
    'ModelEnvironmentDefinitionResponseR',
    'ModelEnvironmentDefinitionResponseSpark',
    'ModelEnvironmentDefinitionSpark',
    'ModelPythonSection',
    'ModelSparkSection',
    'ModelVersionResource',
    'ModelVersionResourceArmPaginatedResult',
    'ModifyExperimentDto',
    'ModifyRunDto',
    'Mpi',
    'NodeStateCounts',
    'OnlineDeploymentProperties',
    'OnlineDeploymentPropertiesDeploymentConfiguration',
    'OnlineDeploymentPropertiesModelReference',
    'OnlineDeploymentPropertiesTrackedResource',
    'OnlineDeploymentPropertiesTrackedResourceArmPaginatedResult',
    'OnlineEndpointProperties',
    'OnlineEndpointPropertiesComputeConfiguration',
    'OnlineEndpointPropertiesTrackedResource',
    'OnlineEndpointPropertiesTrackedResourceArmPaginatedResult',
    'Operation',
    'OperationDisplay',
    'OperationListResult',
    'OutputDatasetLineage',
    'OutputPathAssetReference',
    'PaginatedArtifactContentInformationDto',
    'PaginatedArtifactDto',
    'PaginatedBaseEvent',
    'PaginatedComputeResourcesList',
    'PaginatedExperimentDto',
    'PaginatedLinkedWorkspaceList',
    'PaginatedRunDto',
    'PaginatedRunMetricDto',
    'PaginatedServiceList',
    'ParameterSamplingConfiguration',
    'Password',
    'PipelineJob',
    'PrivateEndpoint',
    'PrivateEndpointConnection',
    'PrivateLinkResource',
    'PrivateLinkResourceListResult',
    'PrivateLinkServiceConnectionState',
    'ProgressMetrics',
    'PyTorch',
    'PythonProperties',
    'QueryParamsDto',
    'QueueingInfoDto',
    'QuotaBaseProperties',
    'QuotaUpdateParameters',
    'RCranPackage',
    'RGitHubPackage',
    'RGitHubPackageResponse',
    'RSection',
    'RSectionResponse',
    'RegenerateEndpointKeysRequest',
    'RegistryListCredentialsResult',
    'ResourceId',
    'ResourceIdentityInArm',
    'ResourceName',
    'ResourceQuota',
    'ResourceSkuLocationInfo',
    'ResourceSkuZoneDetails',
    'Restriction',
    'RootError',
    'RootErrorautogenerated',
    'RunCountsDto',
    'RunDetailsDto',
    'RunDetailsWarningDto',
    'RunDto',
    'RunMetricDto',
    'RunOptions',
    'SQLAdminSection',
    'SSLConfiguration',
    'SSLConfigurationautogenerated',
    'SasSection',
    'ScaleSettings',
    'ScaleSettingsautogenerated',
    'ServicePrincipalCredentials',
    'ServicePrincipalSection',
    'ServiceResource',
    'ServiceResponseBase',
    'ServiceResponseBaseError',
    'SharedPrivateLinkResource',
    'Sku',
    'SkuCapability',
    'SkuListResult',
    'SparkMavenPackage',
    'StatusMessage',
    'SweepJob',
    'SystemData',
    'SystemService',
    'Tensorflow',
    'TerminationConfiguration',
    'TerminationConfigurationEarlyTerminationPolicyConfiguration',
    'TokenResult',
    'TrialJob',
    'TruncationSelectionPolicyConfiguration',
    'UpdateWorkspaceQuotas',
    'UpdateWorkspaceQuotasResult',
    'Usage',
    'UsageName',
    'UserAccountCredentials',
    'UserAssignedIdentity',
    'UserAssignedIdentityMeta',
    'VirtualMachine',
    'VirtualMachineImage',
    'VirtualMachineSecrets',
    'VirtualMachineSize',
    'VirtualMachineSizeListResult',
    'VirtualMachineSshCredentials',
    'VnetConfiguration',
    'VnetConfigurationautogenerated',
    'Workspace',
    'WorkspaceListResult',
    'WorkspaceSku',
    'WorkspaceUpdateParameters',
    'AcquisitionFunction',
    'AllocationState',
    'BatchLoggingLevel',
    'BatchOutputAction',
    'BillingCurrency',
    'CommunicationBackend',
    'ComputeEnvironmentType',
    'ComputeType',
    'ContentsType',
    'CredentialsType',
    'CustomAssetType',
    'DataBindingMode',
    'DatasetConsumptionType',
    'DatasetDeliveryMechanism',
    'DatasetOutputMechanism',
    'DatasetOutputType',
    'DatasetType',
    'DeploymentProvisioningState',
    'DeploymentType',
    'DistributionType',
    'DockerSpecificationType',
    'EarlyTerminationPolicyType',
    'EncryptionStatus',
    'EndpointAuthModeType',
    'EndpointProvisioningState',
    'Enum0',
    'Enum2',
    'Enum3',
    'Enum4',
    'Enum5',
    'EnvironmentSpecificationType',
    'ExperimentQueryParamsDtoViewType',
    'ExportFormatType',
    'FlowType',
    'ImageAnnotationType',
    'JobStatus',
    'JobType',
    'KeyType',
    'LabelExportState',
    'MediaType',
    'NodeState',
    'OptimizationMetric',
    'OrderString',
    'OsType',
    'ParameterSamplingType',
    'PrimaryMetricGoal',
    'PrivateEndpointConnectionProvisioningState',
    'PrivateEndpointServiceConnectionStatus',
    'ProvisioningState',
    'PythonSpecificationType',
    'QuotaUnit',
    'ReasonCode',
    'ReferenceType',
    'RemoteLoginPortPublicAccess',
    'ResourceIdentityType',
    'SSLConfigurationStatus',
    'ScaleTypeMode',
    'Status',
    'StatusMessageLevel',
    'TrainingType',
    'UnderlyingResourceAction',
    'UnitOfMeasure',
    'UsageUnit',
    'UserType',
    'VariantType',
    'VmPriceOsType',
    'VmPriority',
    'VmTier',
    'WebServiceState',
]
