name: cli-e2etest

on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
jobs:
  dev-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - run: |
        az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.59-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
        # NOTE: If the above line number is changed (currently #25), please update installation.rst (cli install instructions is pulled from here)
    - run: az ml -h
    - run: az ml job -h
      continue-on-error: true
    - run: az ml data -h
    - run: az ml datastore -h
    - run: az ml model -h
    - run: az ml environment -h
    - run: az ml endpoint -h
    - run: az ml compute -h
    - run: az ml workspace -h
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_TOKEN}}
    - run: |
          az config set defaults.workspace=e2edemos
          az config set defaults.group=demorg
          az account set -s 92c76a2f-0e1c-4216-b65e-abf7a3f34c1e
    - run: |
          az ml environment create --file examples/train/fastai/pets-resnet34/fastai_vision_env.yml
    - run: |
          az ml environment create --file examples/train/r/r_env.yml
    - run: |
          az ml environment create --file examples/iris/xgboost_env.yml
      continue-on-error: true
    - run: |
          az ml environment create --file examples/train/fastai/mnist-resnet18/fastai_env.yml
      continue-on-error: true

    - run: |
          az ml environment create --file examples/train/tensorflow/tf_env.yml
      continue-on-error: true
    - run: |
          az ml data create --file examples/iris/iris_data.yml
      continue-on-error: true
    - run: |
          az ml job create --file examples/iris/iris_job.yml --name iris_$GITHUB_RUN_ID
    - run: |
          az ml job create --file examples/train/basic-command-job/pip_freeze_job.yml
    - run: |
          az ml job create --file examples/train/basic-command-job/hello_python_job.yml  --name hellotest_$GITHUB_RUN_ID 
# Test fails - needs fix
#     - run: |
#           az ml job create --file examples/train/r/accident-prediction/r_job.yml  --name rtest_$GITHUB_RUN_ID
    - run: |
          az ml job create --file examples/train/fastai/mnist-resnet18/fastai_mnist_job.yml --name fastai_mnist_$GITHUB_RUN_ID 
    - run: |
          az ml data upload --name wikitext-2 --version 1 --path examples/train/pytorch/word-language-model/data/wikitext-2
      continue-on-error: true
    - run: |
          az ml job create --file examples/train/pytorch/word-language-model/job.yml --name pytorch_lm_$GITHUB_RUN_ID
    - run: |
          az ml job create --file examples/sweep/sweepjob.yml --name sweeptest_$GITHUB_RUN_ID 
      continue-on-error: true
      
    - run: |
          az ml model create --file examples/deploy/sklearn/simplemodel.yml -n modeltest_$GITHUB_RUN_ID
      continue-on-error: true

    - run: |
          az ml endpoint create --file examples/deploy/sklearn/basicaksendpoint.yml
      continue-on-error: true
#     - name: Download/Upload nyc_taxi_dataset (just 1 month, 2GB)
#       run: |
#             pip install tqdm
#             python examples/dask/copy_nyc_taxi.py --months 1
    - name: Dask data processing job on small cluster with 4 nodes
      run: |
            az ml job create --file examples/dask/dask-job.yaml --name dask_$GITHUB_RUN_ID