name: sphinx-docs-pr
on:
  pull_request:
    branches:
      - main
    paths: 
      - docs/**
      - sdk2-src/**
      - .github/workflows/sphinx-docs-pr.yml
jobs:
  build:
    name: deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt
        working-directory: docs
      - run: make html
        working-directory: docs
      - uses: actions/upload-artifact@v1
        with:
          name: PR HTML Artifact
          path: docs/_build/html/