name: docs-pr
on:
  pull_request:
    branches:
      - main
    paths: 
      - docs/**
      - sdk2-src/**
      - .github/workflows/sphinx-docs-pr.yml
jobs:
  build:
    name: check documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt
        working-directory: docs
      - run: curl https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.21-py3-none-any.whl --output ml-0.0.21-py3-none-any.whl
        working-directory: docs
      - run: mkdir _build
        working-directory: docs
      - run: python generate.py -e ml-0.0.21-py3-none-any.whl -o _build
        working-directory: docs
      - uses: actions/upload-artifact@v1
        with:
          name: PR HTML Artifact
          path: docs/_build/
