name: docs
on:
  push:
    branches:
      - main
    paths: 
      - docs/**
      - sdk2-src/**
      - .github/**
jobs:
  build:
    name: deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install -r requirements.txt
        working-directory: docs
      - run: curl https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.38-py3-none-any.whl --output ml-0.0.38-py3-none-any.whl
        working-directory: docs
      - run: mkdir _build
        working-directory: docs
      - run: mkdir _build/html
        working-directory: docs
      - run: python generate.py -e ml-0.0.38-py3-none-any.whl -o _build/html
        working-directory: docs
      - run: git config --global user.email "azureml@microsoft.com"
      - run: git config --global user.name "Azure ML"
      - run: git checkout -b docs
      - run: git add -f docs
      - run: git commit -m "adding built sphinx docs"
      - run: git push -uf origin docs
